### ISSUE TITLE
Missing effect on Tails' attack

### ISSUE THREAD

**Issue by michael-fadely** [SonicFreak94/sadx-d3d11#1]

**Comment by michael-fadely** [comment]
fixed with triangle fan implementation

**Comment by PiKeyAr** [comment]
A bit offtopic, but any way to fix this without D3D11? It seems to happen when both Onion Blur and Lantern Engine are enabled.

**Comment by michael-fadely** [comment]
IIRC, it works with _just_ onion blur, so I think something is going wrong in Lantern Engine.
