### ISSUE TITLE
SetMaterialAndSpriteColor_Float not working

### ISSUE THREAD

**Issue by PiKeyAr** [SonicFreak94/sadx-d3d11#6]
I'm using SetMaterialAndSpriteColor_Float to set the color of E101R effects when he evades Gamma's attacks. With the DX11 mod (OIT both on and off), the material colors don't seem to be applied correctly:
![image](https://user-images.githubusercontent.com/23312549/40264971-e3f61f52-5b69-11e8-890c-f5e89b5bfdcb.png)
Here's what it looks like without the DX11 mod:
![image](https://user-images.githubusercontent.com/23312549/40264969-d51749fc-5b69-11e8-947e-b277f9a2febb.png)
The effect uses njColorBlendingMode before rendering to set the source color to NJD_COLOR_BLENDING_SRCALPHA and the destination color to NJD_COLOR_BLENDING_ONE. 
After rendering the color blending mode is reset to NJD_COLOR_BLENDING_SRCALPHA and NJD_COLOR_BLENDING_INVSRCALPHA for source and destination color respectively.

**Comment by PiKeyAr** [comment]
Here's another material color issue. It doesn't use SetMaterialAndSpriteColor but it uses material colors to make the hole black.

**Comment by SonicFreak94** [comment]
This could also explain #2

**Comment by SonicFreak94** [comment]
The E101 effect is working now (and I'm not sure when that changed), but the door remains an issue.

**Comment by PiKeyAr** [comment]
With the previous version of the mod a lot of stuff that used material colors/alpha - for example, the "goal" emerald glow in Windy Valley, Casinopolis and Ice Cap that I added a while back - was invisible. Now it's all functional. So something was definitely fixed.

**Comment by PiKeyAr** [comment]
Also I was wrong about the door. It doesn't use material colors, instead it uses a black texture with no UVs, which makes it fully black without the DX11. With the DX11 mod it turns white, but this seems to be unrelated to material colors, so I guess this can be closed.
