### ISSUE TITLE
Hedgehog Hammer result highlight is triangular instead of rectangular

### ISSUE THREAD

**Issue by PiKeyAr** [SonicFreak94/sadx-d3d11#7]
Happens with OIT on/off
![image](https://user-images.githubusercontent.com/23312549/40265068-0141a638-5b6c-11e8-9910-8d3655d1ed51.png)

**Comment by SonicFreak94** [comment]
This might be due to the type of geometry used for the rectangle. If it's a triangle fan, then I'm incorrectly converting to a triangle list (since triangle fans haven't existed for _thousands of years_)
